export 'src/address/detect.dart';
export 'src/address/validate.dart';
export 'src/address/parse.dart';
export 'src/address/codes.dart';
export 'src/muxed/encode.dart';
export 'src/muxed/decode.dart';
export 'src/routing/extract.dart';
export 'src/routing/result.dart';
export 'src/routing/memo.dart';
