name: stellar_address_kit
description: Dart implementation of the Stellar Address Kit.
version: 1.0.0
repository: https://github.com/stellar-address-kit/core-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
